<a href="https://colab.research.google.com/github/SalinaThapa07/ML-with-python/blob/main/DAY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ones =np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
print(type(ones))

<class 'numpy.ndarray'>


In [ ]:
print(ones.dtype)

float64


In [ ]:
arr1= np.arange(2,21,2)
arr2= np.arange(1,21,2)
print(arr1,arr2)



[ 2  4  6  8 10 12 14 16 18 20] [ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
print (arr1 - arr2)
print (arr1 + arr2)
print (arr1 * arr2)
print (arr1 /arr2)

[1 1 1 1 1 1 1 1 1 1]
[ 3  7 11 15 19 23 27 31 35 39]
[  2  12  30  56  90 132 182 240 306 380]
[2.         1.33333333 1.2        1.14285714 1.11111111 1.09090909
 1.07692308 1.06666667 1.05882353 1.05263158]
